import type { Metadata } from 'next'
import './globals.css'
import localFont from 'next/font/local'
import { Providers } from './providers'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const mainFont = localFont({
  src: './fonts/Helvetica Neue 67 Medium Condensed.otf',
  display: 'swap',
})

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={mainFont.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
